jobs:
  - script: >
      job('bootstrap-job') {
          scm {
            git {
                remote {
                     name('origin')
                     url('https://github.com/AnalogJ/you-dont-know-jenkins-dynamic-kubernetes-slaves.git')
                 }
                branch('complete')

            }
          }
          steps {
            dsl {
                  external('dsl/*.groovy')
                  removeAction('DISABLE')
                  ignoreExisting()
            }
          }
      }
  - script: >
        queue('bootstrap-job')
